//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckinManagementSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int ID { get; set; }
        public Nullable<int> IdNhanSu { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<int> IdLoaiRecord { get; set; }
        public Nullable<int> InOut { get; set; }
    }
}
